---
title: "COVID_POR_SUB_MAPA"
author: "Vitor Veloso"
date: "18/02/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

<http://tabnet.saude.prefeitura.sp.gov.br/cgi/tabcgi.exe?secretarias/saude/TABNET/RCOVID19/covid19.def>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\#\#COVID POR SUB

```{r installer}

library(tidyverse)
# library(devtools)
library(lubridate)


script_dir = dirname(rstudioapi::getActiveDocumentContext()$path)

```

```{r librarys}
#load def files
#install.packages("remotes")
#remotes::install_github("dlill/conveniencefunctions")


library(tidyverse)
library(lubridate)

script_dir = dirname(rstudioapi::getActiveDocumentContext()$path)



```


```{r casos e plotagem}
# casos <- read.csv2(paste0(script_dir,"/A191206201_43_103_106.csv"), na= c(' ','-'))
# casos <- read.csv2(paste0(script_dir,"/Covid_SUB.csv"), na= c(' ','-'))
 # casos <- read.csv2(paste0(script_dir,"/Covid_SUB_DIA.csv"), na= c(' ','-'))
 # casos_semana <- read.csv2(paste0(script_dir,"/Covid_SUB_SEMANA.csv"), na= c(' ','-'))
 
file <- paste0(script_dir,"/Covid_SUB_DIA_05032021_UTF8.csv")
encode <- uchardet::detect_file_enc(file)

casos <- read.table(file,skip = 4, nrows = length(readLines(file)) - 9, na= c(' ','-'),encoding = "Latin1",sep = ";",header = TRUE)

cod_subs <- read.csv2(paste0(script_dir,"/estudo_tratado.csv"),sep=",")



#TETO max value máximoo valor
teto_total <- max(casos %>% 
    select(!c(Ano.Mês.Dia.Inicio.Sint , Total))
  ,na.rm=TRUE) #+ 200

teto <- max(casos[-nrow(casos),] %>% 
    select(!c(Ano.Mês.Dia.Inicio.Sint , Total))
  ,na.rm=TRUE) #+ 200

#subprefeitura <- as.character(colnames(pin_date[1]))
outputDIR <- paste0(script_dir,"/plots")

out_plot <- paste0(script_dir,"/plots","/by_sub/")
out_plot_fixed <- paste0(script_dir,"/plots","/fixed/")


if (!dir.exists(outputDIR)) {dir.create(outputDIR)}
if(!dir.exists(out_plot)){
  dir.create(out_plot
)  }
if(!dir.exists(out_plot_fixed)){
  dir.create(out_plot_fixed
)  }




casos_semana_new <-
  casos_semana %>%
  mutate(semana = gsub("Semana ", "", Sem.Epid.Início.Sintoma)) %>%
  mutate(ano = sub("*..\\/", "", semana)) %>%
  mutate(semana = gsub("\\/.*", "", semana)) %>%
  mutate(ano=year(as.Date(ano,"%Y"))) %>%
  mutate(semana=as.numeric(semana)) %>%
  filter(row_number() <= n()-1)

casos_semana_new <-
  casos_semana_new %>%
  #remove o absurdo no final da tabela
  filter(row_number() <= n()-3)





x<-
casos_semana_new %>%
  mutate(semana = ifelse(ano > year(as.Date("2020","%Y")),semana+ 53,semana ))

casos_semana_new %>%
  year(as.date(ano))


casos_semana_new %>%
mutate(a=year(as.Date(ano,"%Y")))


#   mutate(week = ifelse(year(dia) > year(as.Date("2020","%Y")),weeks+ 53,weeks ))


 
 # #TETO max value máximoo valor
# 
#  teto <- max(casos %>% 
#     select(!c(Ano.Mês.Dia.Inicio.Sint , Total))
#   ,na.rm=TRUE) #+ 200
 



#subprefeitura <- as.character(colnames(pin_date[1]))

# #Loops for subprefeituras
# for(n in seq(2,35)){
# subprefeitura <- as.character(colnames(casos[n]))
# # subprefeitura <- "Pinheiros"
# 
# tmp <-
# casos %>%
#   select(subprefeitura,Ano.Mês.Dia.Inicio.Sint ) %>%
#   mutate(dia=as.Date(Ano.Mês.Dia.Inicio.Sint, "%d/%m/%Y"))%>%
#   #filter(dia >= "2020-05-01")
#   #year(as.Date("2020","%Y"))
#   #year(pin_date$dia) 
#   mutate(weeks=week(dia)) %>%
#   mutate(week = ifelse(year(dia) > year(as.Date("2020","%Y")),weeks+ 53,weeks ))
# 
# 
# 
# tmp <- 
#   tmp %>%
#     group_by(week) %>%
#     summarise(casos=sum(get(subprefeitura),na.rm = TRUE),data=mean(dia))
# 
# 
# 
# ###############
# outputDIR <- paste0(script_dir,"/plots")
# 
# if (!dir.exists(outputDIR)) {dir.create(outputDIR)}
# 
# plot <-
#   tmp %>%
#   filter(!week == "59") %>%
#   ggplot(aes(x = data, y = casos)) +
#   geom_point() +
#   geom_line() +
#   geom_smooth() 
# 
# plot +
#   scale_x_date(date_breaks = "months" , date_labels = "%b-%y") +
#   ggsave(
#     paste0(outputDIR, "/plot_", subprefeitura, ".png") ,
#     width = 50,
#     height = 20,
#     units = "cm"
#   )
# 
# plot +
#   scale_y_continuous(limits = c(0, teto)) +
#   scale_x_date(date_breaks = "months" , date_labels = "%b-%y") +
#   ggsave(
#     paste0(outputDIR, "/plot_", subprefeitura, "_Fixed.png") ,
#     width = 50,
#     height = 20,
#     units = "cm"
#   )
# 
# 
# 
# assign(paste(subprefeitura),tmp,envir=.GlobalEnv)
# 
# 
# 
# #muda nome do dataframe #change data frame name dynamically
# #assign(paste("NEWNAME"),OLDNAME,envir=.GlobalEnv) #outside function
# 
# #assign(paste("oi"),x,envir=.GlobalEnv)
# 
# #end loop subs
# 
# }


```


```{r}


# for(n in seq(2,35)){
# subprefeitura <- as.character(colnames(casos[n]))
subprefeitura <- "Pinheiros"

tmp <-
casos %>%
  # select(subprefeitura,Ano.Mês.Dia.Inicio.Sint ) %>%
  mutate(dia=as.Date(Ano.Mês.Dia.Inicio.Sint, "%d/%m/%Y"))%>%
  #filter(dia >= "2020-05-01")
  #year(as.Date("2020","%Y"))
  #year(pin_date$dia) 
  mutate(weeks=week(dia)) %>%
  mutate(week = ifelse(year(dia) > year(as.Date("2020","%Y")),weeks+ 53,weeks )) %>%
  select(-Ano.Mês.Dia.Inicio.Sint,-weeks)

tmpx <- 
  tmp %>%
    group_by(week) %>%
    filter(n() > 6) %>%
    summarise(casos=sum(get(subprefeitura),na.rm = TRUE),data=mean(dia))

tmp_mean <-
    tmp %>%
    group_by(week) %>%
    filter(n() > 6) %>%
        summarize_all(funs(mean(., na.rm=TRUE)))

as.data.frame(tmp_mean)


# }
```


```{r covert to geo}
#Carrega mapa da cidade
library(sf)

mapa_cidade <- 
  sf::st_read(paste0(script_dir,"/MAPA/DEINFO_SUBPREFEITURAS_2013.shp")) %>%
  st_set_crs(5533) %>%  
  st_transform(4326) 

############################################################################
# #Estudo e criação da lista de codigos

# 
# lista <- list()
# 
# for(n in seq(2,33)){
# subprefeitura <- as.character(colnames(casos[n]))
# lista[[length(lista) + 1]] <- subprefeitura
# }
# 
# <-
# as.data.frame(c(lista,mapa_cidade$NOME))


# head(mapa_cidade$NOME)
# data.frame(Reduce(rbind, lista),tmp2)
# tmp <- 
#   # as.data.frame(mapa_cidade$NOME) %>%
#   data.frame(Reduce(rbind, lista),mapa_cidade$NOME,mapa_cidade$COD_SUBPRE)
# write.csv2(tmp,paste0(script_dir,"/estudo.csv"))
############################################################################

# 
# cod_subs <- read.csv2(paste0(script_dir,"/estudo_tratado.csv"),sep=",")


```

```{r where magic happen}

# test1 <- as.data.frame(tmp_mean[1,],)
# 
# test1 <-
# test1 %>%
#   select(-Ign,-Total,-week) %>%
# #to transpose (Matrix Transpose)
# #?t()
#   t()
# 
# test1
# 
# 
# test2<-
# merge(test1,cod_subs,by.x=0,by.y = "Sub",all = TRUE)
# 
# test2<-
#   test2 %>%
#   mutate(V1=as.numeric(V1)) %>%
#   select(mapa_cidade.COD_SUBPRE,V1)
# 
# x <-
# merge(mapa_cidade,test2,by.x="COD_SUBPRE" ,by.y = "mapa_cidade.COD_SUBPRE",all = TRUE)

```

```{r simplified}

tmp=as.data.frame(tmp_mean) %>%
    select(-Ign,-Total,-week,dia)


#Linha 1
por_linha <- as.data.frame(tmp_mean[1,],)
#loop

colnames(tmp_mean)

dia=por_linha$dia

por_linha <-
por_linha %>%
  select(-Ign,-Total,-week,dia) %>%
  t()

linha_codigo_sub <-
merge(por_linha,cod_subs,by.x=0,by.y = "Sub",all = TRUE) %>%
  mutate(V1=as.numeric(V1)) %>%
  select(mapa_cidade.COD_SUBPRE,V1)

x <-
merge(mapa_cidade,linha_codigo_sub,by.x="COD_SUBPRE" ,by.y = "mapa_cidade.COD_SUBPRE",all = TRUE)



```

```{r for test}
i=10
for(i in 1:nrow(tmp_mean)){
#  print(tmp_mean[i,])
por_linha <- tmp_mean[i,]
#loop
#colnames(tmp_mean)

#dia=por_linha$dia
#transforma em coluna e filtra
por_linha <-
por_linha %>%
  select(-Ign,-Total,-week,dia) %>%
  t()

#pega data
data  = por_linha[nrow(por_linha)]

#remove linha da data
por_linha <-
  por_linha[!row.names(por_linha)%in%"dia",] %>%
  as.data.frame()


linha_codigo_sub <-
merge(por_linha,cod_subs,by.x=0,by.y = "Sub",all = TRUE) %>%
  mutate(!!data := as.numeric(.)) #%>%
  select(mapa_cidade.COD_SUBPRE,!!data )

# as.character()
# 
# linha_codigo_sub <-
# merge(por_linha,cod_subs,by.x=0,by.y = "Sub",all = TRUE) %>%
#   mutate(!!data := as.numeric(V1)) #%>%
#   select(mapa_cidade.COD_SUBPRE,!!data )

x <-
merge(mapa_cidade,linha_codigo_sub,by.x="COD_SUBPRE" ,by.y = "mapa_cidade.COD_SUBPRE",all = FALSE)



 dia 
x  
  
}


```



```{r plot test 1}
  ggplot(x) +
    ggtitle("Casos de covid semana do dia ", dia) +
    geom_sf(data=x,color="transparent", aes(fill=V1,colour = white))+
    geom_sf(color="black",data=mapa_cidade, fill="transparent")+
    scale_fill_gradient(low = "blue", high = "red")
```

